const API="https://ypedqbffumjwccqmgauo.supabase.co/functions/v1/equal-world-api-v2";
let adminToken=sessionStorage.getItem("eqws_admin_token");let selectedShipment=null;let selectedChat=null;
const $=id=>document.getElementById(id);
async function api(action,payload={}){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json","Authorization":adminToken?`Bearer ${adminToken}`:""},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw Error(d.error||"Request failed");return d}
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function showApp(){ $("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("logoutBtn").classList.remove("hidden");loadShipments();loadChats() }
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="Signing in…";try{const d=await api("admin_login",{email:$("email").value.trim(),password:$("password").value});adminToken=d.token||d.access_token;if(!adminToken)throw Error("No admin session token returned.");sessionStorage.setItem("eqws_admin_token",adminToken);showApp()}catch(x){$("loginError").textContent=x.message}};
$("logoutBtn").onclick=()=>{sessionStorage.removeItem("eqws_admin_token");location.reload()};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".tabpane").forEach(x=>x.classList.add("hidden"));$(b.dataset.tab+"Tab").classList.remove("hidden")});
async function loadShipments(){const box=$("shipmentRows");box.innerHTML="<tr><td colspan=6>Loading…</td></tr>";try{const d=await api("admin_shipments");const rows=d.shipments||d.data||[];box.innerHTML=rows.length?rows.map(s=>`<tr><td><strong>${esc(s.tracking_code)}</strong></td><td><span class=statuspill>${esc(s.status)}</span></td><td>${esc(s.origin)}</td><td>${esc(s.destination)}</td><td>${s.updated_at?esc(new Date(s.updated_at).toLocaleString()):"—"}</td><td><button class=ghost onclick='selectShipment(${JSON.stringify(s).replace(/'/g,"&#39;")})'>Manage</button></td></tr>`).join(""):"<tr><td colspan=6>No shipments yet.</td></tr>"}catch(e){box.innerHTML=`<tr><td colspan=6 class=error>${esc(e.message)}</td></tr>`}}
window.selectShipment=s=>{selectedShipment=s;$("selectedShipment").innerHTML=`<div class=selected><p><strong>${esc(s.tracking_code)}</strong></p><p>${esc(s.origin)} → ${esc(s.destination)}</p><p>Status: <span class=statuspill>${esc(s.status)}</span></p><p>Email: ${esc(s.receiver_email||"—")}</p><a target=_blank rel=noopener href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.destination||"")}">Open destination in Google Maps</a></div>`;$("eventForm").classList.remove("hidden");$("event_shipment_id").value=s.id;$("event_status").value=s.status||"In Transit"};
$("shipmentForm").onsubmit=async e=>{e.preventDefault();const p={};["tracking_code","sender_name","receiver_name","receiver_email","origin","destination","service","status","estimated_delivery"].forEach(k=>p[k]=$(k).value.trim());if(!p.tracking_code)p.tracking_code="EWS"+Date.now().toString().slice(-10);$("shipmentFormMsg").textContent="Creating…";try{await api("create_shipment",p);$("shipmentForm").reset();$("service").value="Express Worldwide";$("status").value="Pending";$("shipmentFormMsg").textContent="Shipment created.";loadShipments()}catch(x){$("shipmentFormMsg").textContent=x.message}};
$("eventForm").onsubmit=async e=>{e.preventDefault();$("eventMsg").textContent="Adding…";try{await api("add_shipment_event",{shipment_id:$("event_shipment_id").value,status:$("event_status").value,location:$("event_location").value.trim(),description:$("event_description").value.trim()});$("eventMsg").textContent="Tracking event added.";$("event_location").value="";$("event_description").value="";loadShipments()}catch(x){$("eventMsg").textContent=x.message}};
$("refreshShipments").onclick=loadShipments;
async function loadChats(){const box=$("chatSessions");box.innerHTML="Loading…";try{const d=await api("admin_chat_sessions");const a=d.sessions||d.chat_sessions||d.data||[];box.innerHTML=a.length?a.map(s=>`<div class="session ${selectedChat?.id===s.id?"active":""}" onclick='selectChat(${JSON.stringify(s).replace(/'/g,"&#39;")})'><strong>${esc(s.visitor_name||"Visitor")}</strong><br><small>${esc(s.visitor_email||"")} · ${esc(s.status||"open")}</small></div>`).join(""):"<p class=muted>No conversations yet.</p>"}catch(e){box.innerHTML=`<p class=error>${esc(e.message)}</p>`}}
window.selectChat=async s=>{selectedChat=s;$("chatTitle").textContent=`${s.visitor_name||"Visitor"} — ${s.visitor_email||""}`;$("replyForm").classList.remove("hidden");loadChats();await loadChatMessages()};
async function loadChatMessages(){if(!selectedChat)return;try{const d=await api("admin_chat_messages",{session_id:selectedChat.id});const a=d.messages||d.data||[];$("adminMessages").innerHTML=a.map(m=>`<div class="msg ${m.sender=== "visitor"?"visitor":"agent"}"><strong>${m.sender==="visitor"?esc(selectedChat.visitor_name||"Visitor"):"You"}</strong><p>${esc(m.message)}</p><small>${m.sent_at?esc(new Date(m.sent_at).toLocaleString()):""}</small></div>`).join("")||"<p class=muted>No messages.</p>";$("adminMessages").scrollTop=$("adminMessages").scrollHeight}catch(e){$("replyMsg").textContent=e.message}}
$("replyForm").onsubmit=async e=>{e.preventDefault();const msg=$("replyInput").value.trim();if(!msg||!selectedChat)return;$("replyMsg").textContent="Sending…";try{await api("admin_chat_reply",{session_id:selectedChat.id,message:msg});$("replyInput").value="";$("replyMsg").textContent="Sent.";await loadChatMessages();await loadChats()}catch(x){$("replyMsg").textContent=x.message}};
$("refreshChats").onclick=loadChats;
if(adminToken)showApp();
